apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ambassador-deployment
spec:
  template:
    metadata:
      labels:
        app: ambassador-example
    spec:
      containers:
        - name: application
          image: redis
        - name: ambassador
          image: malexer/twemproxy
          env:
            - name: REDIS_SERVERS
              value: redis-st-0.redis-svc.default.svc.cluster.local:6379:1 redis-st-1.redis-svc.default.svc.cluster.local:6379:1
          ports:
            - containerPort: 6380
  selector:
    matchLabels:
      app: ambassador-example
