apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment

spec:
  selector:
    matchLabels:
      app: nginx-topz
  template:
    metadata:
      labels:
        app: nginx-topz
    spec:
      # application and sidecar containers in the same pod sharing proccess namespace
      shareProcessNamespace: true
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 500Mi
              cpu: 1
        - name: topz
          image: brendanburns/topz:db0fa58
          ports:
            - containerPort: 8080
          command: ["/server", "--addr=0.0.0.0:8080"]
          resources:
            limits:
              memory: 200Mi
              cpu: 1