apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish-cache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: varnish-cache
  template:
    metadata:
      labels:
        app: varnish-cache
    spec:
      containers:
      - name: cache
        image: brendanburns/varnish
        resources:
          requests:
            memory: 1Gi
        ports:
          - containerPort: 8080
        command:
          - varnishd
          - -F
          - -f
          - /etc/varnish-config/varnish-config.vcl
          - -a
          - 0.0.0.0:8080
          - -s
          - malloc,1G
        volumeMounts:
          - name: varnish
            mountPath: /etc/varnish-config
      volumes:
        - name: varnish
          configMap:
            name: varnish-config