apiVersion: v1
kind: Service
metadata:
  name: dictionary-server-service
spec:
  type: NodePort
  selector:
    app: dictionary-server
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30005
